### ISSUE TITLE
error in Add window in Fedora Linux 30

### ISSUE THREAD

**Issue by ijgnd** [lovac42/CCBC#10]
**I don't get this error in Windows with the binary you provided `CCBC_Win_x64_v0.0.4_beta.7z`.** 

So this is maybe out of scope and maybe there's something about my dependencies on my system. But maybe you have an idea? Thanks.

&nbsp;

I tested in Fedora 30 with the latest commit 81300a9 (`Anki 2.1.14_ccbc (0.0.4) Python 3.7.3 Qt 4.8.7 PyQt 4.12.3`. ) and an empty profile without add-ons: After adding the first note I get these errors: https://streamable.com/iy2f1

I looked at the sourcecode and don't really understand the sip module and the line [if sip.isdeleted(self.completer)](https://github.com/lovac42/CCBC/blob/master/aqt/tagedit.py#L85). I commented out this if-loop and so far (a few hours) I haven't seen any problems. This if-loop was added last year to counter some occasional errors, see [anki commit eca6ecf](https://github.com/dae/anki/commit/eca6ecf90faea01014fbe4f1a9d339a190ef97cb).

error I get when I press the Add button:

```python
Caught exception:
  File "/home/fifi/CCBC/aqt/addcards.py", line 207, in addCards
    self.editor.saveAddModeVars()
  File "/home/fifi/CCBC/aqt/editor.py", line 477, in saveAddModeVars
    m = self.note.model()
<class 'AttributeError'>: 'NoneType' object has no attribute 'model'
```

error I get when I click on an entry in the history list:

```python
Caught exception:
  File "/home/fifi/CCBC/aqt/addcards.py", line 170, in <lambda>
    a.triggered.connect(lambda b, nid=nid: self.editHistory(nid))
  File "/home/fifi/CCBC/aqt/addcards.py", line 178, in editHistory
    browser = aqt.dialogs.open("Browser", self.mw)
  File "/home/fifi/CCBC/aqt/__init__.py", line 71, in open
    instance = creator(*args)
  File "/home/fifi/CCBC/aqt/browser.py", line 380, in __init__
    self.onSearch()
  File "/home/fifi/CCBC/aqt/browser.py", line 558, in onSearch
    self.model.search(txt, reset)
  File "/home/fifi/CCBC/aqt/browser.py", line 125, in search
    self.beginReset()
  File "/home/fifi/CCBC/aqt/browser.py", line 152, in beginReset
    self.browser.editor.setNote(None, hide=False)
  File "/home/fifi/CCBC/aqt/editor.py", line 316, in setNote
    self.hideCompleters()
  File "/home/fifi/CCBC/aqt/editor.py", line 482, in hideCompleters
    self.tags.hideCompleter()
  File "/home/fifi/CCBC/aqt/tagedit.py", line 85, in hideCompleter
    if sip.isdeleted(self.completer):
<class 'TypeError'>: isdeleted() argument 1 must be sip.simplewrapper, not TagCompleter
```

error when I press the close button:

```python
Caught exception:
  File "/home/fifi/CCBC/aqt/addcards.py", line 234, in reject
    self.editor.setNote(None)
  File "/home/fifi/CCBC/aqt/editor.py", line 316, in setNote
    self.hideCompleters()
  File "/home/fifi/CCBC/aqt/editor.py", line 482, in hideCompleters
    self.tags.hideCompleter()
  File "/home/fifi/CCBC/aqt/tagedit.py", line 85, in hideCompleter
    if sip.isdeleted(self.completer):
<class 'TypeError'>: isdeleted() argument 1 must be sip.simplewrapper, not TagCompleter
```

**Comment by lovac42** [comment]
I've tested this on Debian and Slackware with no problems, so it specific to Fedora 30. I'll try to get a copy and test it out this week, but it looks like those lines are added to fix a race condition for 2.1 and Qt5 and may not be needed for Qt4. They are not in the source code for 2.0.

**Comment by ijgnd** [comment]
Thanks for your help. As I said I commented it out and so far haven't noticed any problems.

I tested with this setup (installation instructions for Fedora 30 XFCE spin):

1. Download Fedora 30 XFCE from https://download.fedoraproject.org/pub/fedora/linux/releases/30/Spins/x86_64/iso/Fedora-Xfce-Live-x86_64-30-1.2.iso (link via https://spins.fedoraproject.org/xfce/download/)
2. Install the following packages: `sudo dnf install git python3-PyQt4-webkit python3-beautifulsoup4 python3-pyaudio python3-send2trash python3-requests python3-decorator python3-markdown python3-jsonschema python3-six python3-sip`
3. run `git clone https://github.com/lovac42/CCBC`, then `python3 CCBC/runanki`.

I thought about trying on CentOS7 but I figured that since it lacks python3 I should miss many packages.

**Comment by lovac42** [comment]
Thanks for the heads up and the links. I did get what you were saying, just trying to look for a better solution so it doesn't come back to haunt me later on. And it looks to be specific to that version of PyQt, so the latest update should fix it. Removing those lines work just as well, but there's always a what-if...

CentOS7... Honestly with FOSS, any package that is missing could be complied and added manually from source. Just depends on how much free time you have and how much you are willing to devote to finding dependencies. Which is why I just stick to Windows. The constancy is reassuring.
